parameters:

    light_cms_core.backend_module.node_bundle.node:
        name: node
        title: Nodes
        bundle: LightCMSNodeBundle
        controller: Node
        search_entity: node
        entities:
            node:
                class: LightCMS\NodeBundle\Entity\Node
                repository: LightCMSNodeBundle:Node
                form_type: node
            page:
                class: LightCMS\NodeBundle\Entity\Page
                repository: LightCMSNodeBundle:Page
                form_type: page
            folder:
                class: LightCMS\NodeBundle\Entity\Folder
                repository: LightCMSNodeBundle:Folder
                form_type: folder


        tree:
            repository: 'LightCMSNodeBundle:Node'
            id: salt
            name: name
            parent: parent
        icon: 'glyphicon glyphicon-home'

    inheritance_joined_map.node:
        node:
            entity: LightCMS\NodeBundle\Entity\Node
            map:
                folder:
                    class: LightCMS\NodeBundle\Entity\Folder
                    shortclass: Folder
                    controller: LightCMSNodeBundle:Folder
                page:
                    class: LightCMS\NodeBundle\Entity\Page
                    shortclass: Page
                    controller: LightCMSNodeBundle:Page

services:

    light_cms_node.form_type.node_type:
        class: LightCMS\NodeBundle\Form\Type\NodeType
        tags:
            - { name: form.type, alias: node }

    light_cms_node.form_type.folder_type:
        class: LightCMS\NodeBundle\Form\Type\FolderType
        tags:
            - { name: form.type, alias: folder }

    light_cms_node.form_type.page_type:
        class: LightCMS\NodeBundle\Form\Type\PageType
        tags:
            - { name: form.type, alias: page }