light_cms_core_home:
    path:     /
    defaults: { _controller: LightCMSCoreBundle:Node:view }

light_cms_core_page:
    path:     /node/{path}
    defaults: { _controller: LightCMSCoreBundle:Node:view }
    requirements:
        path: ".+"