light_cms_backend:
    path: /backend
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_slash:
    path: /backend/
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_entity_action:
    path: /backend/{entity}/{action}
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_entity_action_id:
    path: /backend/{entity}/{action}/{id}
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_entity_action_id_param:
    path: /backend/{entity}/{action}/{id}/{params}
    defaults:
        _controller: LightCMSCoreBundle:Backend:index
    requirements:
        params: ".*"

#light_cms_core_frontend:
#    path: /{module}/{path}
#    defaults:
#        _controller: LightCMSCoreBundle:Frontend:view
#        module: null
#        path: null
#    requirements:
#        path: ".+"
