# BACKEND Login

light_cms_backend_user_login:
    path: /backend/user/login
    defaults:
        _controller: LightCMSUserBundle:Login:back

light_cms_backend_user_check:
    path: /backend/user/check

light_cms_backend_user_logout:
    path: /backend/user/logout

# BACKEND Routing

light_cms_backend:
    path: /backend
    defaults:
        _controller: LightCMSCoreBundle:Core:backend

light_cms_backend_slash:
    path: /backend/
    defaults:
        _controller: LightCMSCoreBundle:Core:backend


light_cms_backend_module:
    path: /backend/{module}/{subModule}/{action}
    defaults:
        _controller: LightCMSCoreBundle:Core:backend

light_cms_backend_module_action:
    path: /backend/{module}/{subModule}/{action}/{params}
    defaults:
        _controller: LightCMSCoreBundle:Core:backend
    requirements:
        params: ".*"

# FRONT Login

light_cms_frontend_user_login:
    path: /user/login
    defaults:
        _controller: LightCMSUserBundle:Login:front

light_cms_frontend_user_check:
    path: /user/check

light_cms_frontend_user_logout:
    path: /user/logout


# FRONT Routing

light_cms_frontend:
    path: /{path}
    defaults:
        _controller: LightCMSCoreBundle:Core:frontend
        path: null
    requirements:
        path: ".+"
