light_cms_core_home:
    path:     /
    defaults: { _controller: LightCMSCoreBundle:Page:view }

light_cms_core_page:
    path:     /page/{path}
    defaults: { _controller: LightCMSCoreBundle:Page:view }
    requirements:
        path: ".+"