light_cms_core_backend:
    path: /backend/{module}/{action}/{id}
    defaults:
        _controller: LightCMSCoreBundle:Backend:view
        module: node
        action: admin
        id : null

light_cms_core_frontend:
    path: /{module}/{path}
    defaults:
        _controller: LightCMSCoreBundle:Frontend:view
        module: null
        path: null
    requirements:
        path: ".+"
