light_cms_core_backend:
    path: /backend/{action}/{module}/{id}
    defaults:
        _controller: LightCMSCoreBundle:Backend:index
        action: dashboard
        module: dashboard
        id : null


light_cms_core_frontend:
    path: /{module}/{path}
    defaults:
        _controller: LightCMSCoreBundle:Frontend:view
        module: null
        path: null
    requirements:
        path: ".+"
