light_cms_backend:
    path: /backend
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_slash:
    path: /backend/
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_module:
    path: /backend/{module}/{subModule}/{action}
    defaults:
        _controller: LightCMSCoreBundle:Backend:index

light_cms_backend_module_action:
    path: /backend/{module}/{subModule}/{action}/{params}
    defaults:
        _controller: LightCMSCoreBundle:Backend:index
    requirements:
        params: ".*"

#light_cms_core_frontend:
#    path: /{module}/{path}
#    defaults:
#        _controller: LightCMSCoreBundle:Frontend:view
#        module: null
#        path: null
#    requirements:
#        path: ".+"
