parameters:

    light_cms.modules.core_bundle:
        lcms:
            menu:
                Dashboard:
                    icon: 'glyphicon glyphicon-dashboard'
                    route: light_cms_backend
                    params: []
            backend:
                dashboard: LightCMSCoreBundle:Dashboard


services:

    light_cms_core.service.parameters_service:
        class: LightCMS\CoreBundle\Service\ParametersService
        arguments:
            - @service_container

    light_cms_core.service.module_service:
        class: LightCMS\CoreBundle\Service\ModuleService
        arguments:
            - @service_container

    light_cms_core.service.generate_url:
        class: LightCMS\CoreBundle\Service\LightCMSUrlService
        arguments:
            - @service_container

    discriminator_map:
        class: LightCMS\CoreBundle\Listener\DiscriminatorMapListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    light_cms_core.form_type.infinite_form_polycollection:
        class: LightCMS\CoreBundle\Form\Type\PolyCollectionType
        tags:
            - { name: form.type, alias: infinite_form_polycollection }

    light_cms_core.form_type.modal_entity:
        class: LightCMS\CoreBundle\Form\Type\ModalEntityType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: modal_entity }

    light_cms_core.twig.lcms_extension:
        class: LightCMS\CoreBundle\Twig\LightCMSExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }