parameters:

    light_cms.modules.core_bundle:
        node:
            repository: LightCMSCoreBundle:Node
            orderby:
                name: ASC
            parent: parent
            menu:
                Nodes:
                    icon: 'fa fa-sitemap'
                    route: light_cms_backend_module
                    params:
                        module: node
                        subModule: node
                        action: list
            backend:
                node: LightCMSCoreBundle:Node
            frontend: LightCMSCoreBundle:Node:view

    light_cms.javascript.core_bundle:
        global:
            - bundles/lightcmscore/js/bind.jquery.js
        frontend:
            - bundles/lightcmscore/js/frontend.js
        backend:
            - bundles/lightcmscore/js/backend.js

    light_cms.stylesheet.core_bundle:
        frontend:
            - bundles/lightcmscore/css/frontend.css
        backend:
            - bundles/lightcmscore/css/backend.css


services:

    light_cms_core.event_listener.file_event_listener:
        class: LightCMS\CoreBundle\EventListener\FileEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    light_cms_core.event_listener.file_image_event_listener:
        class: LightCMS\CoreBundle\EventListener\FileImageEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    light_cms_core.service.parameters_service:
        class: LightCMS\CoreBundle\Service\ParametersService
        arguments:
            - @service_container

    light_cms_core.service.module_service:
        class: LightCMS\CoreBundle\Service\ModuleService
        arguments:
            - @service_container

    light_cms_core.service.generate_url:
        class: LightCMS\CoreBundle\Service\LightCMSUrlService
        arguments:
            - @service_container

    discriminator_map:
        class: LightCMS\CoreBundle\Listener\DiscriminatorMapListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    light_cms_core.form_type.infinite_form_polycollection:
        class: LightCMS\CoreBundle\Form\Type\PolyCollectionType
        tags:
            - { name: form.type, alias: infinite_form_polycollection }

    light_cms_core.form_type.modal_entity:
        class: LightCMS\CoreBundle\Form\Type\ModalEntityType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: modal_entity }

    light_cms_page.form_type.file_upload_type:
        class: LightCMS\CoreBundle\Form\Type\FileType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: file_upload }

    light_cms_page.form_type.file_image_type:
        class: LightCMS\CoreBundle\Form\Type\FileImageType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: file_image }

    light_cms_page.form_type.node_type:
        class: LightCMS\CoreBundle\Form\Type\NodeType
        tags:
            - { name: form.type, alias: node }

    light_cms_core.twig.lcms_extension:
        class: LightCMS\CoreBundle\Twig\LightCMSExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }