parameters:
    discriminator_map:
        person:
            entity: LightCMS\CoreBundle\Entity\Node
            map:
                page: LightCMS\PageBundle\Entity\Page
                folder: LightCMS\FolderBundle\Entity\Folder

services:

    lcms.discriminator_map:
        class: LightCMS\CoreBundle\Listener\DiscriminatorMapListener
        arguments:
            - [%discriminator_map%]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    service.site:
        class:     LightCMS\CoreBundle\Service\SiteService
        arguments:
            - @service_container