parameters:

    light_cms.modules.core_bundle:
        dashboard:
            menu:
                title: Dashboard
                icon: 'glyphicon glyphicon-dashboard'
                link:
                    route: light_cms_backend
                    params: []
            path: dashboard
            controller:
                backend: LightCMSCodeBundle:Dashboard:view


services:

    light_cms_core.service.parameters_service:
        class: LightCMS\CoreBundle\Service\ParametersService
        arguments:
            - @service_container

    light_cms_core.service.module_service:
        class: LightCMS\CoreBundle\Service\ModuleService
        arguments:
            - @service_container

    discriminator_map:
        class: LightCMS\CoreBundle\Listener\DiscriminatorMapListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    class_guesser:
        class: LightCMS\CoreBundle\Service\ClassGuesserService

    light_cms_core.form_type.field_group_type:
        class: LightCMS\CoreBundle\Form\Type\FieldGroupType
        tags:
            - { name: form.type, alias: fieldgroup }

    light_cms_core.form_type.infinite_form_polycollection:
        class: LightCMS\CoreBundle\Form\Type\PolyCollectionType
        tags:
            - { name: form.type, alias: infinite_form_polycollection }
