services:
#    light_cms_core.example:
#        class: LightCMS\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    service.site:
        class:     LightCMS\CoreBundle\Service\SiteService
        arguments:
            - @service_container