services:

    light_cms_core.service.parameters_service:
        class: LightCMS\CoreBundle\Service\ParametersService
        arguments:
            - @service_container

    discriminator_map:
        class: LightCMS\CoreBundle\Listener\DiscriminatorMapListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    class_guesser:
        class: LightCMS\CoreBundle\Service\ClassGuesserService


    light_cms_core.form_type.html_type:
        class: LightCMS\CoreBundle\Form\Type\HtmlType
        tags:
            - { name: form.type, alias: html }

    light_cms_core.form_type.action_type:
        class: LightCMS\CoreBundle\Form\Type\ActionType
        tags:
            - { name: form.type, alias: action }