services:

    discriminator_map:
        class: LightCMS\CoreBundle\Listener\DiscriminatorMapListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    class_guesser:
        class: LightCMS\CoreBundle\Service\ClassGuesserService

    service.site:
        class:     LightCMS\CoreBundle\Service\SiteService
        arguments:
            - @service_container