light_cms_node:
    resource: "@LightCMSNodeBundle/Resources/config/routing.yml"
    prefix:   /

light_cms_site:
    resource: "@LightCMSSiteBundle/Resources/config/routing.yml"
    prefix:   /

light_cms_core:
    resource: "@LightCMSCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
