light_cms_user:
    resource: "@LightCMSUserBundle/Resources/config/routing.yml"
    prefix:   /

light_cms_core:
    resource: "@LightCMSCoreBundle/Resources/config/routing.yml"
    prefix:   /

#light_cms_page:
#    resource: "@LightCMSPageBundle/Resources/config/routing.yml"
#    prefix:   /

#light_cms_media:
#    resource: "@LightCMSMediaBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
