security:
    encoders:
        LightCMS\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        lightcms_provider:
            entity:
                class: LightCMSUserBundle:User
                property: email

    firewalls:
        back_secured_area:
            context: backend
            pattern: ^/backend
            form_login:
                check_path: /backend/user/check
                login_path: /backend/user/login
                provider: lightcms_provider
                default_target_path: /backend
            logout:
                path:   /backend/user/logout
                target: /backend
            anonymous: ~

        front_secured_area:
            context: frontend
            pattern: ^/
            form_login:
                check_path: /user/check
                login_path: /user/login
                provider: lightcms_provider
            logout:
                path:   /user/logout
                target: /
            anonymous: true

#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
