parameters:

    light_cms.inheritance.pagebundle:
        page:
            content:
                name: Content Page
                icon: 'fa fa-file-code-o'
                entity: LightCMS\PageBundle\Entity\PageContent
                controllers:
                    view: LightCMSPagebundle:PageContent:view
                    create: LightCMSPagebundle:PageContent:create
                    edit: LightCMSPagebundle:PageContent:edit
                    delete: LightCMSPagebundle:PageContent:delete
                templates:
                    view: LigheCMSPageBundle:PageContent:view.html.twig
            site:
                name: Site
                icon: 'fa fa-globe'
                entity: LightCMS\PageBundle\Entity\Site
                controllers:
                    view: LightCMSPagebundle:Site:view
                    create: LightCMSPagebundle:Site:create
                    edit: LightCMSPagebundle:Site:edit
                    delete: LightCMSPagebundle:Site:delete
                templates:
                    view: LigheCMSPageBundle:Site:view.html.twig
        row:
            widget:
                name: Widget Row
                entity: LightCMS\PageBundle\Entity\RowWidget
                controllers:
                    view: LightCMSPagebundle:RowWidget:view
                    create: LightCMSPagebundle:RowWidget:create
                    edit: LightCMSPagebundle:RowWidget:edit
                    delete: LightCMSPagebundle:RowWidget:delete
                templates:
                    view: LigheCMSPageBundle:RowWidget:view.html.twig
        widget:
            content:
                name: Content Widget
                entity: LightCMS\PageBundle\Entity\WidgetContent
                controllers:
                    view: LightCMSPagebundle:WidgetContent:view
                    create: LightCMSPagebundle:WidgetContent:create
                    edit: LightCMSPagebundle:WidgetContent:edit
                    delete: LightCMSPagebundle:WidgetContent:delete
                templates:
                    view: LigheCMSPageBundle:WidgetContent:view.html.twig

    light_cms.modules.pagebundle:
        node:
            backend:
                page: LightCMSPageBundle:Page
                site: LightCMSPageBundle:Site
                version: LightCMSPageBundle:Version
                widget: LightCMSPageBundle:Widget
                widgetcontent: LightCMSPageBundle:WidgetContent


services:

#    light_cms_site.service.site_service:
#        class: LightCMS\PageBundle\Service\SiteService
#        arguments:
#            - @service_container


    light_cms_page.form_type.site_type:
        class: LightCMS\PageBundle\Form\Type\SiteType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: site }

    light_cms_page.form_type.page_type:
        class: LightCMS\PageBundle\Form\Type\PageType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: page }

    light_cms_page.form_type.version_type:
        class: LightCMS\PageBundle\Form\Type\VersionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: version }

    light_cms_page.form_type.row_type:
        class: LightCMS\PageBundle\Form\Type\RowType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: row }

    light_cms_page.form_type.widget_type:
        class: LightCMS\PageBundle\Form\Type\WidgetType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: widget }

    light_cms_page.form_type.widget_content_type:
        class: LightCMS\PageBundle\Form\Type\WidgetContentType
        tags:
            - { name: form.type, alias: widgetcontent }

