parameters:

    light_cms.inheritance.pagebundle:
        node:
            - page
            - site
        widget:
            - widgetcontent

    light_cms.modules.pagebundle:
        node:
            menu:
                Nodes:
                    icon: 'fa fa-sitemap'
                    route: light_cms_backend_module
                    params:
                        module: node
                        subModule: node
                        action: dashboard
            backend:
                node: LightCMSPageBundle:Node
                page: LightCMSPageBundle:Page
                site: LightCMSPageBundle:Site
                version: LightCMSPageBundle:Version
            frontend: LightCMSPageBundle:Node:view

services:

#    light_cms_site.service.site_service:
#        class: LightCMS\PageBundle\Service\SiteService
#        arguments:
#            - @service_container

    light_cms_page.form_type.node_type:
        class: LightCMS\PageBundle\Form\Type\NodeType
        tags:
            - { name: form.type, alias: node }

    light_cms_page.form_type.site_type:
        class: LightCMS\PageBundle\Form\Type\SiteType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: site }

    light_cms_page.form_type.page_type:
        class: LightCMS\PageBundle\Form\Type\PageType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: page }

    light_cms_page.form_type.version_type:
        class: LightCMS\PageBundle\Form\Type\VersionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: version }

    light_cms_page.form_type.row_type:
        class: LightCMS\PageBundle\Form\Type\RowType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: row }

    light_cms_page.form_type.widget_type:
        class: LightCMS\PageBundle\Form\Type\WidgetType
        tags:
            - { name: form.type, alias: widget }

    light_cms_page.form_type.widget_content_type:
        class: LightCMS\PageBundle\Form\Type\WidgetContentType
        tags:
            - { name: form.type, alias: widgetcontent }

