parameters:

    light_cms.entities.pagebundle:
        node:
            class: LightCMS\PageBundle\Entity\Node
            repository: LightCMSPageBundle:Node
            module: page
            idfield: salt
            name: [ 'name' ]
            form: node
            templates:
                edit: LightCMSPageBundle:Node:edit.html.twig
                view: LightCMSPageBundle:Node:view.html.twig
        site:
            icon: 'glyphicon glyphicon-globe'
            class: LightCMS\PageBundle\Entity\Site
            repository: LightCMSPageBundle:Site
            controller: LightCMSPageBundle:Site
            module: page
            idfield: salt
            name: [ 'name' ]
            form: site
            templates:
                edit: LightCMSPageBundle:Site:edit.html.twig
                view: LightCMSPageBundle:Site:view.html.twig
        page:
            icon: 'glyphicon glyphicon-file'
            class: LightCMS\PageBundle\Entity\Page
            repository: LightCMSPageBundle:Page
            controller: LightCMSPageBundle:Page
            module: page
            idfield: salt
            name: [ 'name' ]
            form: page
            templates:
                edit: LightCMSPageBundle:Page:edit.html.twig
                view: LightCMSPageBundle:Page:view.html.twig
        version:
            class: LightCMS\PageBundle\Entity\Version
            repository: LightCMSPageBundle:Version
            controller: LightCMSPageBundle:Version
            module: page
            idfield: id
            form: version
            templates:
                edit: LightCMSPageBundle:Version:edit.html.twig
                view: LightCMSPageBundle:Version:view.html.twig

    light_cms.inheritance.pagebundle:
        node:
            - page
            - site
        widget:
            - widgetcontent

    light_cms.modules.pagebundle:
        node:
            menu:
                Nodes:
                    icon: 'glyphicon glyphicon-file'
                    tree: LightCMSPageBundle:Node:tree
            submodules:
                page: LightCMSPageBundle:Page
                site: LightCMSPageBundle:Site
                version: LightCMSPageBundle:Version


services:

#    light_cms_site.service.site_service:
#        class: LightCMS\PageBundle\Service\SiteService
#        arguments:
#            - @service_container

    light_cms_page.form_type.node_type:
        class: LightCMS\PageBundle\Form\Type\NodeType
        tags:
            - { name: form.type, alias: node }

    light_cms_page.form_type.site_type:
        class: LightCMS\PageBundle\Form\Type\SiteType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: site }

    light_cms_page.form_type.page_type:
        class: LightCMS\PageBundle\Form\Type\PageType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: page }

    light_cms_page.form_type.version_type:
        class: LightCMS\PageBundle\Form\Type\VersionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: version }

    light_cms_page.form_type.row_type:
        class: LightCMS\PageBundle\Form\Type\RowType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: row }

    light_cms_page.form_type.widget_type:
        class: LightCMS\PageBundle\Form\Type\WidgetType
        tags:
            - { name: form.type, alias: widget }

    light_cms_page.form_type.widget_content_type:
        class: LightCMS\PageBundle\Form\Type\WidgetContentType
        tags:
            - { name: form.type, alias: widgetcontent }

