parameters:
    discriminator_map.page:
        node:
            entity: LightCMS\CoreBundle\Entity\Node
            map:
                page: LightCMS\PageBundle\Entity\Page


services:
    light_cms_page.form_type.page_type:
        class: LightCMS\PageBundle\Form\Type\PageType
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: page }
