parameters:

    light_cms.inheritance.pagebundle:
        node:
            page:
                type: page
                name: Content Page
                icon: 'fa fa-file-code-o'
                entity: LightCMS\PageBundle\Entity\Page
                repository: LightCMSPageBundle:Page
                form: page
                controllers:
                    view: LightCMSPageBundle:Page:view
                    create: LightCMSPageBundle:Page:create
                    edit: LightCMSPageBundle:Page:edit
                    delete: LightCMSPageBundle:Page:delete
                templates:
                    view: LigheCMSPageBundle:Page:view.html.twig
                    edit: LightCMSPageBundle:Page:edit.html.twig
        version:
            header:
                type: versionheader
                name: Header Version
                icon: 'fa fa-file-code-o'
                entity: LightCMS\PageBundle\Entity\VersionHeader
                repository: LightCMSPageBundle:VersionHeader
                form: versionheader
            rows:
                type: versionrows
                name: Rows Version
                icon: 'fa fa-file-code-o'
                entity: LightCMS\PageBundle\Entity\VersionRows
                repository: LightCMSPageBundle:VersionRows
                form: versionrows

        row:
            widget:
                name: Widget Row
                entity: LightCMS\PageBundle\Entity\RowWidget
                controllers:
                    view: LightCMSPagebundle:RowWidget:view
                    create: LightCMSPagebundle:RowWidget:create
                    edit: LightCMSPagebundle:RowWidget:edit
                    delete: LightCMSPagebundle:RowWidget:delete
                templates:
                    view: LigheCMSPageBundle:RowWidget:view.html.twig
        widget:
            content:
                name: Content Widget
                entity: LightCMS\PageBundle\Entity\WidgetContent
                controllers:
                    view: LightCMSPagebundle:WidgetContent:view
                    create: LightCMSPagebundle:WidgetContent:create
                    edit: LightCMSPagebundle:WidgetContent:edit
                    delete: LightCMSPagebundle:WidgetContent:delete
                templates:
                    view: LigheCMSPageBundle:WidgetContent:view.html.twig

    light_cms.modules.pagebundle:
        node:
            backend:
                page: LightCMSPageBundle:Page
                version: LightCMSPageBundle:Version
                versionheader: LightCMSPageBundle:VersionHeader
                versionrows: LightCMSPageBundle:VersionRows
                row: LightCMSPageBundle:Row
                widget: LightCMSPageBundle:Widget
                widgetcontent: LightCMSPageBundle:WidgetContent


services:

    light_cms_page.form_type.page_type:
        class: LightCMS\PageBundle\Form\Type\PageType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: page }

    light_cms_page.form_type.version_header_type:
        class: LightCMS\PageBundle\Form\Type\VersionHeaderType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: versionheader }

    light_cms_page.form_type.version_rows_type:
        class: LightCMS\PageBundle\Form\Type\VersionRowsType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: versionrows }

    light_cms_page.form_type.version_type:
        class: LightCMS\PageBundle\Form\Type\VersionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: version }

    light_cms_page.form_type.row_type:
        class: LightCMS\PageBundle\Form\Type\RowType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: row }

    light_cms_page.form_type.widget_type:
        class: LightCMS\PageBundle\Form\Type\WidgetType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: widget }

    light_cms_page.form_type.widget_content_type:
        class: LightCMS\PageBundle\Form\Type\WidgetContentType
        tags:
            - { name: form.type, alias: widgetcontent }

