parameters:
    light_cms_core.backend_module.site:
        name: site
        title: Sites
        bundle: LightCMSSiteBundle
        controller: Site
        tree:
            repository: 'LightCMSSiteBundle:Site'
            id: id
            name: title
        icon: 'glyphicon glyphicon-globe'

services:

    light_cms_site.service.site_service:
        class: LightCMS\SiteBundle\Service\SiteService
        arguments:
            - @service_container

    light_cms_site.form_type.site_type:
        class: LightCMS\SiteBundle\Form\Type\SiteType
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: site }