parameters:

    light_cms.inheritance.userbundle:
        user:
            user:
                type: user
                name: User
                icon: 'fa fa-user'
                entity: LightCMS\UserBundle\Entity\User
                repository: LightCMSUserBundle:User
                form: user
        group:
            group:
                type: group
                name: Group
                icon: 'fa fa-users'
                entity: LightCMS\UserBundle\Entity\Group
                repository: LightCMSUserBundle:Group
                form: group

    light_cms.modules.userbundle:
        user:
            repository: LightCMSUserBundle:User
            orderby:
                lastname: ASC
                firstname: ASC
            menu:
                Users:
                    icon: 'fa fa-user'
                    route: light_cms_backend_module
                    params:
                        module: user
                        subModule: user
                        action: list
            backend:
                user: LightCMSUserBundle:User

        group:
            repository: LightCMSUserBundle:Group
            orderby:
                name: ASC
            menu:
                Groups:
                    icon: 'fa fa-users'
                    route: light_cms_backend_module
                    params:
                        module: group
                        subModule: group
                        action: list
            backend:
                group: LightCMSUserBundle:Group

services:

    light_cms_user.event_listener.user_event_listener:
        class: LightCMS\UserBundle\EventListener\UserEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    light_cms_user.form_type.user_type:
        class: LightCMS\UserBundle\Form\Type\UserType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: user }

    light_cms_user.form_type.group_type:
        class: LightCMS\UserBundle\Form\Type\GroupType
        arguments:
            - @service_container
        tags:
            - { name: form.type, alias: group }
